spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Auth Service
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/users/**

            # Employee Service
            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/employees/**
            
            # Address Service
            - id: address-service
              uri: lb://ADDRESS-SERVICE
              predicates:
                - Path=/api/addresses/**

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
